#!/bin/bash

# :script: remote_AQMS_event_mag_query.sh
# :auth: Nathan T Stevens
# :email: ntsteven (at) uw.edu
# :org: Pacific Northwest Seismic Network
# :license: CC-BY-4.0

# ATTRIBUTION: 
# This script modified from code generated by ChatGPT-3.5 using
# the following prompt:

# """
# You (N. Stevens)
# write a bash script that gets a vector of values from a CSV file 
# column and uses that vector as the argument for an IN() statement 
# in a psql query
# """

# This script executes a query on the PNSN PostgreSQL AQMS databases to
# retrieve analyst reviewed, labeled event and phase data to train/test/validate
# E3WS models.

# It MUST be run on the standby postprocessing AQMS server.

# The TABLE join model is:
# input.CSV -Evid|evid-> EVENT -prefor|orid-> ORIGIN -orid-> ASSOCAR -arid-> ARRIVAL
#                          |
#                          - prefmag|magid-> NETMAG

# See CISN/ANSS Parametric Information Model for more information:
# https://ncedc.org/db/Documents/NewSchemas/PI/v1.6.4/PI.1.6.4/index.htm
# '

# Check if the required number of arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input_csv_file>"
    echo "E.g., $0 pnsn_event_export_20231117.csv"
    exit 1
fi

# Assign input arguments to variables
input_csv_file="$1"

# Define database name and user name for simplicity
database="archdb"
psql_user="browser"


# Assign input arguments to variables
input_csv_file="$1"
column_name="Evid"
output_csv_file="$2"

# Check if the input CSV file exists
if [ ! -f "$input_csv_file" ]; then
    echo "Error: Input CSV file '$input_csv_file' not found."
    exit 1
fi

# Read unique values from the specified column in the CSV file and create a comma-separated list
values=$(tail -n +2 "$input_csv_file" | cut -d ',' -f "$(head -n 1 "$input_csv_file" | tr ',' '\n' | grep -n "$column_name" | cut -d ':' -f 1)" | sort -u | paste -sd ',')

# Construct the psql query
query="\copy (  SELECT e.evid, o.orid, n.magid,
                     n.magnitude, n.magtype, n.uncertainty,
                     n.nsta, n.nobs,
                     o.lat, o.lon, o.depth, o.datetime,
                     o.erhor, o.erlat, o.erlon, o.sdep, o.gap,
                     o.quality, o.ndef, o.nbs,
                     o.nbfm, o.fdepth, o.fepi
                FROM event e, origin o, netmag n
                WHERE e.evid IN ($values)
                    AND o.orid = e.prefor
                    AND e.selectflag=1
                    AND n.magid=e.prefmag)
                TO 'AQMS_event_mag_query_output.csv' WITH CSV HEADER;"
# echo "$query"

# Execute the query
psql -d $database -U $psql_user -c "$query"

echo "Script completed successfully."
