name: E3WS
channels:
  - anaconda 
  - conda-forge
  - apple
dependencies:
  - python = 3.8
  - pip 
  - pip: 
    - xgboost==1.6.1
    - scipy==1.8.1
    - python-speech-features==0.6
    - scikit-learn==1.1.1
    - PyGeodesy==23.3.23
    - obspy==1.3.0